change_control_type:
  fields:
    control_type:
      required: true
      default: "NO_SELECTION"
      selector:
        select:
          options:
            - "NO_SELECTION"
            - "FILL_RATE_BASED_CONTROL"
trigger_and_get_schedule:
  fields:
    soc_at_start:
      required: true
      selector:
        number:

send_frbc_instruction:
  fields:
    id:
      required: true
      selector:
        text:
    message_id:
      required: true
      selector:
        text:
    actuator_id:
      required: true
      selector:
        text:
    operation_mode:
      required: true
      selector:
        text:
    operation_mode_factor:
      required: true
      default: 0
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          mode: "slider"
    execution_time:
      required: true
      selector:
          datetime: