name: "Create release"

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+\.dev[0-9]+'  # Match tags that resemble a dev version
      - 'v[0-9]+\.[0-9]+\.[0-9]+'  # Match tags that resemble a version

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ github.ref_name }}
